name: finpayconnect_seller
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Keep this version
  provider: ^6.0.0  # For state management
  shared_preferences: ^2.0.7  # For storing user sessions
  flutter_secure_storage: ^5.0.2  # Secure local storage
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  sqflite: ^2.2.5  # SQLite plugin for Flutter
  path_provider: ^2.0.12  # Provides paths for storing databases
  email_validator: ^2.0.1  # For email validation
  fluttertoast: ^8.2.8  # For showing toast messages
  intl: ^0.19.0
  sqflite_common_ffi: ^2.0.0
  mailer: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/bg.jpg
